apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:3.5.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_ADVERTISED_LISTENERS
 #         value: PLAINTEXT://74.225.32.180:30092
          value: PLAINTEXT://kafka.infra.svc.cluster.local:9092 
---
apiVersion: v1
kind: Service
metadata:
  namespace: infra
  name: kafka
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka

